apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp-deployment
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeserver
          image: darshanwohlig/devops-assessment:main-a660485c6d9c486a302cc3275b44c72c26b64a78
          ports:
            - containerPort: 8080
