apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJkYXJzaGFud29obGlnIiwicGFzc3dvcmQiOiIyMDIzIiwiZW1haWwiOiJkYXJzaGFuLmdhZGFAd29obGlnLmNvbS5jb20iLCJhdXRoIjoiWkdGeWMyaGhibmR2YUd4cFp6b3lNREl6In19fQ==
kind: Secret
metadata:
  creationTimestamp: "2024-01-15T07:26:27Z"
  name: mycreds
  namespace: default
  resourceVersion: "67590"
  uid: 934794d6-a06b-4f5f-be02-c0784ba2e863
type: kubernetes.io/dockerconfigjson
