name: Publish Docker Image to Docker Hub
 
on:
  push:
    branches: ['main']
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - name: Set env
        run: echo "GITHUB_BRANCH=$(echo $GITHUB_REF_NAME-$GITHUB_SHA)" >> $GITHUB_ENV  
 
      - name: Checkout code
        uses: actions/checkout@v3
 
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
 
      - name: Set Image Tag
        run: |
          IMAGE_TAG="op-$(date +%Y%m%d%H%M%S)" # Custom tag name
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV
 
      - name: Build the Docker image
        run: |
          docker build -t $IMAGE_TAG .
          docker tag $IMAGE_TAG ${{ secrets.DOCKER_USERNAME }}/devops-assessment:$IMAGE_TAG
 
      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-assessment:$IMAGE_TAG
 
      - name: Update manifest file
        run: |
          yq e '.spec.template.spec.containers[0].image = "darshanwohlig/devops-assessment:${{ env.GITHUB_BRANCH }}"' -i deployment.yml
 
          git config --global user.email "darshan.gada@wohlig.com"
          git config --global user.name "darshanwohlig19"
          git add .
          git commit -m "new"
          git push
       