name: Publish Docker Image to Docker Hub

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Image Tag
        run: |
          IMAGE_TAG="op-$(date +%Y%m%d%H%M%S)" # Custom tag name
          echo "IMAGE_TAG=$IMAGE_TAG" >> $GITHUB_ENV

      - name: Build the Docker image
        run: |
          docker build -t $IMAGE_TAG .
          docker tag $IMAGE_TAG ${{ secrets.DOCKER_USERNAME }}/devops-assessment:$IMAGE_TAG

      - name: Update manifest file
        run: |
          sed -i 's|devops-assessment:new_tag|op:$IMAGE_TAG|g' ../deployment.yml

      - name: Docker Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/devops-assessment:$IMAGE_TAG
